server:
  port: 8090
  contextPath: /hello-spring-mvc

#If you had preferred .properties file, application.properties corresponding to above .yml would be
#server.port: 8090
#server.contextPath: /hello-spring-mvc
#for more properties check : http://docs.spring.io/autorepo/docs/spring-boot/current/reference/htmlsingle/#using-boot-using-springbootapplication-annotation
